ALTER TABLE `tau_test`.`informes` ADD COLUMN `sql` VARCHAR(2000) AFTER `group_by`;

ALTER TABLE `tau_test`.`informes` MODIFY COLUMN `_select` VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
 MODIFY COLUMN `campos` VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
 MODIFY COLUMN `_from` VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL;
