<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    //protected  $defer = true;

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        echo 'Se ha llamado a boot() de AppServiceProvider: '. get_class($this->app->make('Tests\Integration\Providers\Alguien')).PHP_EOL;
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        echo 'Se ha llamado a register() de AppServiceProvider: '.$this->app->environment().PHP_EOL;

        if( $this->app->environment() === 'testing' ){
            $this->app->bind('Tests\Integration\Providers\Alguien', 'Tests\Integration\Providers\Pepe');
        }else {
            $this->app->bind('Tests\Integration\Providers\Alguien', 'Tests\Integration\Providers\Paco');
        }

        /*$this->app->when('Modules\Administration\Http\Controllers')
            ->needs('$quien')
            ->give($this->app->make('Alguien'));*/
    }

    public function provides()
    {
        echo 'Se ha llamado a provides() de AppServiceProvider'.PHP_EOL;
        return parent::provides(); // TODO: Change the autogenerated stub
    }
}
